apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: service-pipeline-run-1
spec:
  serviceAccountName: dockerconfig
  workspaces:
    - name: sources
      volumeClaimTemplate: 
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi 
    - name: dockerconfig
      secret:  
        secretName: regcred
    - name: maven-settings
      emptyDir: {}
  pipelineRef:
    name: frontend-service-pipeline
  
